'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class add_employee

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbldate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtfirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfirstname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblfirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfirstname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtlastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlastname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbllastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllastname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtfamilyname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfamilyname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblfamilyname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfamilyname As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbgender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbgender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblgender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblgender As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtemail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblemail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbirthdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbirthdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblbirthdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbirthdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbdep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbdep As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblcmbdep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcmbdep As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcategory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblcategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcategory As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbmilitry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbmilitry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblcmbmilitry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcmbmilitry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtqual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtqual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblqual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblqual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtexpyear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtexpyear As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblexpyear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblexpyear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbmarital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbmarital As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblcmbmarital control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcmbmarital As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtblood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtblood As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblblood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblblood As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtnation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblnation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtuser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtuser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbluser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbluser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtpass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtpass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblpass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpass As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbstatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtadd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtadd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbladd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbladd As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btncreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btncreate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsave As Global.System.Web.UI.WebControls.Label
End Class
